inherit_from: .rubocop_todo.yml

AllCops:
  UseCache: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.3

  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "config/initializers/doorkeeper.rb"
    - "config/initializers/simple_form.rb"
    - "config/initializers/simple_form_bootstrap.rb"
    - "db/migrate/20160816183457_create_doorkeeper_tables.rb"

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/WordArray:
  Enabled: false
