language: ruby

cache: bundler

before_script:
  - make install
  - bundle exec rubocop .

rvm:
  - 2.3.1

services:
  - postgresql

after_success:
  bundle exec codeclimate-test-reporter

addons:
  postgresql: "9.4"
